/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "serial.h"


#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define BUFFER_SIZE 64

int main(void)
{
	//Part 2.3.2a - Transmission:
	
	SerialInitialise(BAUD_115200, &USART1_PORT, &finished_transmission);
 
 	//Write a string to send:
	uint8_t * string_to_send = "Transmission string test \r\n";

	//Use transmission function to send it:
	SerialOutputString(string_to_send, &USART1_PORT);
	*/

	//Part 2.3.2a - Receiving
	/*
 	SerialInitialise(BAUD_115200, &USART1_PORT, &finished_receiving);

	char buffer[BUFFER_SIZE];
	SerialInputString(BUFFER_SIZE, &USART1_PORT, buffer);

	for(;;);
 	*/
 	
}

