/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "serial.h"


#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
	//uint8_t *string_to_send = "This is a string !\r\n";

	//void (*completion_function)(uint32_t) = &finished_transmission;

	SerialInitialise(BAUD_115200, &USART1_PORT, &finished_receiving);

	enable_USART_interrupt();

	while (1) {

		for (volatile uint32_t i = 0; i < 500000; i++) { /* Delay */ }
	}

	//initialise buffer
	//uint8_t buffer_size = 64;
	//char buffer[buffer_size];

	//start Receiving
	//SerialInputString(buffer_size, &USART1_PORT, buffer);

	/* Loop forever */
	for(;;);

}

